import danielxavier887Img from "../public/images/danielxavier887.webp";

export const reviews = [
  {
    id: 1,
    avatar: danielxavier887Img,
    reviewer: "haidari23",
    country: "United States",
    rating: 5,
    date: "Feb 18, 2024",
    review: "Rate is fair",
  },
  {
    id: 2,
    avatar: danielxavier887Img,
    reviewer: "haidari23",
    country: "United States",
    rating: 5,
    date: "Feb 13, 2024",
    review: "He is a great guy. wish him good luck. He did an amazing job.",
  },
  {
    id: 3,
    avatar: danielxavier887Img,
    reviewer: "mf_holdings",
    country: "United States",
    rating: 5,
    date: "Jan 28, 2024",
    review: "Great help",
  },
  {
    id: 4,
    avatar: danielxavier887Img,
    reviewer: "kevinmiller7201",
    country: "United States",
    rating: 5,
    date: "Jan 20, 2024",
    review: "he helped build the code",
  },
  {
    id: 5,
    avatar: danielxavier887Img,
    reviewer: "nftyco",
    country: "Mexico",
    rating: 5,
    date: "Nov 04, 2023",
    review: "Great response time and quick turnaround!",
  },
  {
    id: 6,
    avatar: danielxavier887Img,
    reviewer: "danielxavier887",
    country: "Germany",
    rating: 5,
    date: "Sep 25, 2023",
    review: "As always, great work!",
  },
  {
    id: 7,
    avatar: danielxavier887Img,
    reviewer: "danielxavier887",
    country: "Germany",
    rating: 5,
    date: "Sep 25, 2023",
    review:
      "As always, great to work – happy to keep the work with Rakibul. Thanks a lot!",
  },
  {
    id: 8,
    avatar: danielxavier887Img,
    reviewer: "suhasdas",
    country: "United States",
    rating: 5,
    date: "Aug 11, 2023",
    review: "very knowledgeable in MERN. I will continue working with him.",
  },
  {
    id: 9,
    avatar: danielxavier887Img,
    reviewer: "yongyi520",
    country: "United States",
    rating: 5,
    date: "Jun 14, 2023",
    review:
      "Working with him feels amazing He understands what you wanted and did not question much at all And after a while, he will just let you know the job is done. After simple revision, we were able to get the work exactly how I wanted! highly recommended",
  },
];
